Revert "pass already initialized db cursor to Ratelimit.find() trying to fix AttributeError: 'NoneType' object has no attribute 'read'"
This reverts commit ba823356c0e56e229e05b10e983bad721a775a28.